tcpWindowSize=8
maxSegments=24
socksPort=0
autoShutdown=false
vidExts=MP4,M3U8,F4M,WEBM,OGG,MP3,AAC,FLV,MKV,DIVX,MOV,MPG,MPEG,OPUS
speedLimit=0
downloadFolder=/home/jonathanvideoDownloader/
autoStart=false
version=7.0.1
monitoring=true
socksHost=
proxyUser=
proxyPass=
execCmd=false
duplicateAction=0
minVidSize=1048576
maxDownloads=100
fileExts=3GP,7Z,AVI,BZ2,DEB,DOC,DOCX,EXE,GZ,ISO,MSI,PDF,PPT,PPTX,RAR,RPM,XLS,XLSX,SIT,SITX,TAR,JAR,ZIP
proxyPac=
vidUrls=.facebook.com|pagelet,player.vimeo.com/,instagram.com/p/
showDownloadWindow=true
minSegmentSize=65536
showVideoNotification=true
execAntivir=false
language=en
proxyPort=0
showDownloadCompleteWindow=true
proxyMode=0
proxyHost=
keepAwake=false
blockedHosts=update.microsoft.com,windowsupdate.com,thwawte.com
networkTimeout=120
